name: EGNN-DGL
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - pip=21.2.4
  - pytorch=1.10.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
      - -e .
      - dgl-cu113 -f https://data.dgl.ai/wheels/repo.html