name: EGNN-DGL
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python==3.9
  - pip==21.2.4
  - pytorch==1.9.1
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - pip:
      - -e .
      - dgl-cu111 -f https://data.dgl.ai/wheels/repo.html